name: Create Hello World File

on:
  schedule:
    - cron: '00 12 * * 5' # Runs at 10:40 UTC every Friday
  workflow_dispatch:
  
jobs:
  create-file:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Write Hello World to file
      run: echo "Hello, World!" > hello_world.txt
      
    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add hello_world.txt
        git commit -m "Add Hello World file"
        git push https://${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git ${{ github.ref }}
