name: Delete File

on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    - cron: '10 12 * * 5' # Scheduled for 12:10 every Friday

permissions:
  contents: write # This workflow has write permissions to the repository contents
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Delete file
      run: |
        rm data/Bor_Vratanar.csv
      
    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Delete example.txt file"
        git push
