name: Delete Data Folder

on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    - cron: '55 12 * * 5' # Scheduled for 12:10 every Friday

permissions:
  contents: write # This workflow has write permissions to the repository contents
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Delete data folder if exists
      run: |
        [ -d data ] && rm -r data
      
    - name: Commit and push if there are changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git diff --exit-code || (git commit -am "Delete data folder" && git push)
