name: Create Hello World File

on:
  schedule:
    - cron: '55 10 * * 5' # Runs at 10:40 UTC every Friday

jobs:
  create-file:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Write Hello World to file
      run: echo "Hello, World!" > hello_world.txt
      
    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add hello_world.txt
        git commit -m "Add Hello World file"
        git push
